require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PokerCardsController do

  # This should return the minimal set of attributes required to create a valid
  # PokerCard. As you add validations to PokerCard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "player" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PokerCardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all poker_cards as @poker_cards" do
      poker_card = PokerCard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:poker_cards).should eq([poker_card])
    end
  end

  describe "GET show" do
    it "assigns the requested poker_card as @poker_card" do
      poker_card = PokerCard.create! valid_attributes
      get :show, {:id => poker_card.to_param}, valid_session
      assigns(:poker_card).should eq(poker_card)
    end
  end

  describe "GET new" do
    it "assigns a new poker_card as @poker_card" do
      get :new, {}, valid_session
      assigns(:poker_card).should be_a_new(PokerCard)
    end
  end

  describe "GET edit" do
    it "assigns the requested poker_card as @poker_card" do
      poker_card = PokerCard.create! valid_attributes
      get :edit, {:id => poker_card.to_param}, valid_session
      assigns(:poker_card).should eq(poker_card)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PokerCard" do
        expect {
          post :create, {:poker_card => valid_attributes}, valid_session
        }.to change(PokerCard, :count).by(1)
      end

      it "assigns a newly created poker_card as @poker_card" do
        post :create, {:poker_card => valid_attributes}, valid_session
        assigns(:poker_card).should be_a(PokerCard)
        assigns(:poker_card).should be_persisted
      end

      it "redirects to the created poker_card" do
        post :create, {:poker_card => valid_attributes}, valid_session
        response.should redirect_to(PokerCard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved poker_card as @poker_card" do
        # Trigger the behavior that occurs when invalid params are submitted
        PokerCard.any_instance.stub(:save).and_return(false)
        post :create, {:poker_card => { "player" => "invalid value" }}, valid_session
        assigns(:poker_card).should be_a_new(PokerCard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PokerCard.any_instance.stub(:save).and_return(false)
        post :create, {:poker_card => { "player" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested poker_card" do
        poker_card = PokerCard.create! valid_attributes
        # Assuming there are no other poker_cards in the database, this
        # specifies that the PokerCard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PokerCard.any_instance.should_receive(:update).with({ "player" => "" })
        put :update, {:id => poker_card.to_param, :poker_card => { "player" => "" }}, valid_session
      end

      it "assigns the requested poker_card as @poker_card" do
        poker_card = PokerCard.create! valid_attributes
        put :update, {:id => poker_card.to_param, :poker_card => valid_attributes}, valid_session
        assigns(:poker_card).should eq(poker_card)
      end

      it "redirects to the poker_card" do
        poker_card = PokerCard.create! valid_attributes
        put :update, {:id => poker_card.to_param, :poker_card => valid_attributes}, valid_session
        response.should redirect_to(poker_card)
      end
    end

    describe "with invalid params" do
      it "assigns the poker_card as @poker_card" do
        poker_card = PokerCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PokerCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => poker_card.to_param, :poker_card => { "player" => "invalid value" }}, valid_session
        assigns(:poker_card).should eq(poker_card)
      end

      it "re-renders the 'edit' template" do
        poker_card = PokerCard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PokerCard.any_instance.stub(:save).and_return(false)
        put :update, {:id => poker_card.to_param, :poker_card => { "player" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested poker_card" do
      poker_card = PokerCard.create! valid_attributes
      expect {
        delete :destroy, {:id => poker_card.to_param}, valid_session
      }.to change(PokerCard, :count).by(-1)
    end

    it "redirects to the poker_cards list" do
      poker_card = PokerCard.create! valid_attributes
      delete :destroy, {:id => poker_card.to_param}, valid_session
      response.should redirect_to(poker_cards_url)
    end
  end

end
